require 'digest'
require 'fileutils'
require 'json'
require 'net/http'
require 'os'
require 'uri'
require 'zlib'

module Fastlane
  module Helper
    # Downloads and caches the standalone Sentry CLI (https://github.com/getsentry/cli).
    #
    # The plugin pins a CLI version in `sentry-cli.json` (generated by `script/update-sentry-cli.sh`)
    # together with the SHA-256 checksum of every supported release asset. On first use the
    # matching asset is downloaded from GitHub Releases, verified and extracted into a cache
    # directory shared by all projects on the machine.
    class SentryCliInstaller
      MANIFEST_PATH = File.expand_path('../sentry-cli.json', __dir__)
      CACHE_DIR_ENV = 'SENTRY_FASTLANE_PLUGIN_CACHE_DIR'.freeze
      MAX_REDIRECTS = 5

      class << self
        def manifest
          @manifest ||= JSON.parse(File.read(MANIFEST_PATH))
        end

        # The CLI version pinned by this plugin release.
        def version
          manifest['version']
        end

        # Name of the release asset for the current host, e.g. `sentry-darwin-arm64.gz`.
        def asset_name
          os = host_os
          arch = host_arch
          UI.user_error!(unsupported_host_message) if os.nil? || arch.nil?

          suffix = os == 'windows' ? '.exe' : ''
          name = "sentry-#{os}-#{arch}#{suffix}.gz"
          UI.user_error!(unsupported_host_message) unless manifest['assets'].key?(name)
          name
        end

        def download_url
          "#{manifest['repo']}/releases/download/#{version}/#{asset_name}"
        end

        def cache_dir
          custom = ENV.fetch(CACHE_DIR_ENV, nil)
          return File.expand_path(custom) unless custom.to_s.empty?

          base = if OS.windows? && !ENV.fetch('LOCALAPPDATA', '').empty?
                   ENV.fetch('LOCALAPPDATA')
                 elsif !ENV.fetch('XDG_CACHE_HOME', '').empty?
                   ENV.fetch('XDG_CACHE_HOME')
                 else
                   File.join(Dir.home, '.cache')
                 end
          File.join(base, 'sentry-fastlane-plugin')
        end

        # Path the CLI executable is installed to for the pinned version.
        def executable_path
          File.join(cache_dir, 'sentry-cli', version, asset_name.delete_suffix('.gz'))
        end

        # Returns the path to a verified CLI executable, downloading it first if necessary.
        def ensure_installed!
          path = executable_path
          return path if File.executable?(path)

          FileUtils.mkdir_p(File.dirname(path))
          File.open("#{path}.lock", File::RDWR | File::CREAT, 0644) do |lock|
            lock.flock(File::LOCK_EX)
            # Another process may have finished the download while we waited for the lock.
            install!(path) unless File.executable?(path)
          end
          path
        end

        private

        def install!(path)
          url = download_url
          expected_checksum = manifest['assets'][asset_name]
          archive_path = "#{path}.#{Process.pid}.gz"
          extracted_path = "#{path}.#{Process.pid}.tmp"

          UI.message("Downloading Sentry CLI #{version} from #{url}")
          download(url, archive_path)
          verify_checksum!(archive_path, expected_checksum, url)

          Zlib::GzipReader.open(archive_path) do |gz|
            File.open(extracted_path, 'wb') { |file| IO.copy_stream(gz, file) }
          end
          File.chmod(0755, extracted_path)
          File.rename(extracted_path, path)
          UI.message("Installed Sentry CLI #{version} to #{path}")
        ensure
          FileUtils.rm_f([archive_path, extracted_path])
        end

        def verify_checksum!(file, expected, url)
          actual = Digest::SHA256.file(file).hexdigest
          return if actual == expected

          UI.user_error!("Checksum mismatch for #{url}: expected #{expected}, got #{actual}. " \
                         "The download may be corrupted or tampered with. Please try again.")
        end

        def download(url, destination, redirects_left = MAX_REDIRECTS)
          uri = URI.parse(url)
          Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == 'https', open_timeout: 30, read_timeout: 120) do |http|
            request = Net::HTTP::Get.new(uri)
            request['User-Agent'] = "sentry-fastlane-plugin/#{Fastlane::Sentry::VERSION}"

            http.request(request) do |response|
              case response
              when Net::HTTPRedirection
                UI.user_error!("Too many redirects while downloading #{url}") if redirects_left.zero?
                location = URI.join(url, response['location']).to_s
                return download(location, destination, redirects_left - 1)
              when Net::HTTPSuccess
                File.open(destination, 'wb') do |file|
                  response.read_body { |chunk| file.write(chunk) }
                end
              else
                UI.user_error!("Failed to download Sentry CLI from #{url}: HTTP #{response.code} #{response.message}. " \
                               "If this machine has no access to GitHub, install the Sentry CLI manually and pass its path via `sentry_cli_path`.")
              end
            end
          end
        rescue SocketError, SystemCallError, Timeout::Error, OpenSSL::SSL::SSLError => e
          UI.user_error!("Failed to download Sentry CLI from #{url}: #{e.message}. " \
                         "If this machine has no access to GitHub, install the Sentry CLI manually and pass its path via `sentry_cli_path`.")
        end

        def host_os
          if OS.mac?
            'darwin'
          elsif OS.windows?
            'windows'
          elsif OS.linux?
            'linux'
          end
        end

        def host_arch
          case OS.host_cpu.to_s.downcase
          when 'x86_64', 'x64', 'amd64'
            'x64'
          when 'arm64', 'aarch64'
            'arm64'
          end
        end

        def unsupported_host_message
          "The Sentry CLI does not provide a prebuilt binary for this host (#{OS.host_os}/#{OS.host_cpu}). " \
            "Supported hosts: #{manifest['assets'].keys.map { |name| name.delete_suffix('.gz') }.join(', ')}. " \
            "Install the Sentry CLI manually and pass its path via `sentry_cli_path` (or the SENTRY_CLI_PATH environment variable)."
        end
      end
    end
  end
end
