lane :test do
  sentry_upload_dsym(
    dsym_path: './assets/SwiftExample.app.dSYM.zip'
  )
end

lane :test_big do
  sentry_upload_dsym(
    dsym_path: './assets/Big.app.dSYM.zip'
  )
end

lane :integration_test_upload_dif do
  sentry_upload_dif(
    org_slug: 'sentry-sdks',
    project_slug: 'sentry-fastlane-plugin',
    auth_token: 'dummy-auth-token',
    path: './assets/SwiftExample.app.dSYM.zip',
    url: "http://127.0.0.1:8000"
  )
end

lane :integration_test_create_release do
  sentry_create_release(
    org_slug: 'sentry-sdks',
    project_slug: 'sentry-fastlane-plugin',
    auth_token: 'dummy-auth-token',
    version: '1.1.0',
    app_identifier: "com.sentry.fastlane.app",
    url: "http://127.0.0.1:8000"
  )
end
