name: Changelog Preview
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled
permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  changelog-preview:
    uses: getsentry/craft/.github/workflows/changelog-preview.yml@5cabbe7d6ae3730788393284d5071969d9309753 # v2
    secrets: inherit
