name: test

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install sentry-cli
        run: curl -sL https://sentry.io/get-cli/ | bash

      - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: "3.3.11"

      - run: bundle install
      - run: sentry-cli info --config-status-json
      - run: bundle exec rubocop
      - run: rspec
