name: test

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install sentry-cli
        run: curl -sL https://sentry.io/get-cli/ | bash

      - uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
        with:
          ruby-version: "3.1.4"

      - run: gem install bundler -v '2.6.8'
      - run: bundle install
      - run: sentry-cli info --config-status-json
      - run: bundle exec rubocop
      - run: rspec
